# Generated by Django 6.0 on 2026-06-22 16:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('konten', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita_images/')),
                ('tanggal_dibuat', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Rilis Berita')),
            ],
            options={
                'verbose_name_plural': 'Berita',
            },
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Jurusan',
            },
        ),
        migrations.CreateModel(
            name='KontakPesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pesan', models.TextField()),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Daftar Pesan Masuk',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('handphone', models.CharField(default='', max_length=13)),
                ('email', models.EmailField(max_length=50)),
                ('nim', models.CharField(max_length=12)),
                ('timestamp', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('match_played', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('total_poin', models.IntegerField(default=0)),
                ('id_jur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.jurusan')),
            ],
            options={
                'verbose_name_plural': 'Mahasiswa',
            },
        ),
    ]
