# Generated by Django 6.0 on 2026-05-16 07:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Berita',
            },
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Jurusan',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('handphone', models.CharField(default='', max_length=13)),
                ('email', models.EmailField(max_length=50)),
                ('nim', models.CharField(max_length=12)),
                ('timestamp', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_jur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.jurusan')),
            ],
            options={
                'verbose_name_plural': 'Mahasiswa',
            },
        ),
    ]
