# Generated by Django 6.0 on 2026-06-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='tim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
