# Generated by Django 6.0 on 2026-05-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={},
        ),
    ]
