# Generated by Django 6.0 on 2026-06-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_mahasiswa_tim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berita',
            old_name='konten',
            new_name='isi',
        ),
    ]
