# Generated by Django 6.0 on 2026-05-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_berita_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={'verbose_name_plural': 'Berita'},
        ),
        migrations.RenameField(
            model_name='berita',
            old_name='isi',
            new_name='konten',
        ),
        migrations.RenameField(
            model_name='berita',
            old_name='tanggal',
            new_name='tanggal_dibuat',
        ),
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='berita_images/'),
        ),
    ]
