# Generated by Django 6.0 on 2026-05-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_berita_options_rename_isi_berita_konten_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontakPesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pesan', models.TextField()),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Daftar Pesan Masuk',
            },
        ),
    ]
