# Generated by Django 6.0 on 2026-05-31 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_kontakpesan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='tanggal_dibuat',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Rilis Berita'),
        ),
    ]
